// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

package hello

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Arguments struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Arguments) Reset()         { *m = Arguments{} }
func (m *Arguments) String() string { return proto.CompactTextString(m) }
func (*Arguments) ProtoMessage()    {}
func (*Arguments) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{0}
}

func (m *Arguments) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Arguments.Unmarshal(m, b)
}
func (m *Arguments) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Arguments.Marshal(b, m, deterministic)
}
func (m *Arguments) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Arguments.Merge(m, src)
}
func (m *Arguments) XXX_Size() int {
	return xxx_messageInfo_Arguments.Size(m)
}
func (m *Arguments) XXX_DiscardUnknown() {
	xxx_messageInfo_Arguments.DiscardUnknown(m)
}

var xxx_messageInfo_Arguments proto.InternalMessageInfo

// Greeting on random language
type GreetingMessage struct {
	Greetings            string   `protobuf:"bytes,1,opt,name=greetings,proto3" json:"greetings,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetingMessage) Reset()         { *m = GreetingMessage{} }
func (m *GreetingMessage) String() string { return proto.CompactTextString(m) }
func (*GreetingMessage) ProtoMessage()    {}
func (*GreetingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{1}
}

func (m *GreetingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetingMessage.Unmarshal(m, b)
}
func (m *GreetingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetingMessage.Marshal(b, m, deterministic)
}
func (m *GreetingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetingMessage.Merge(m, src)
}
func (m *GreetingMessage) XXX_Size() int {
	return xxx_messageInfo_GreetingMessage.Size(m)
}
func (m *GreetingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GreetingMessage proto.InternalMessageInfo

func (m *GreetingMessage) GetGreetings() string {
	if m != nil {
		return m.Greetings
	}
	return ""
}

func init() {
	proto.RegisterType((*Arguments)(nil), "twirp.example.hello.Arguments")
	proto.RegisterType((*GreetingMessage)(nil), "twirp.example.hello.GreetingMessage")
}

func init() { proto.RegisterFile("hello.proto", fileDescriptor_61ef911816e0a8ce) }

var fileDescriptor_61ef911816e0a8ce = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x48, 0xcd, 0xc9,
	0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x2e, 0x29, 0xcf, 0x2c, 0x2a, 0xd0, 0x4b,
	0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49, 0xd5, 0x03, 0x4b, 0x29, 0x71, 0x73, 0x71, 0x3a, 0x16, 0xa5,
	0x97, 0xe6, 0xa6, 0xe6, 0x95, 0x14, 0x2b, 0xe9, 0x73, 0xf1, 0xbb, 0x17, 0xa5, 0xa6, 0x96, 0x64,
	0xe6, 0xa5, 0xfb, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x0a, 0xc9, 0x70, 0x71, 0xa6, 0x43, 0x85,
	0x8a, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x10, 0x02, 0x46, 0xa9, 0x5c, 0x1c, 0x30, 0x0d,
	0x42, 0x91, 0x5c, 0x82, 0xee, 0xa9, 0x25, 0x41, 0x89, 0x79, 0x29, 0xf9, 0xb9, 0x70, 0x41, 0x39,
	0x3d, 0x2c, 0x96, 0xea, 0xc1, 0x6d, 0x94, 0x52, 0xc1, 0x2a, 0x8f, 0xe6, 0x08, 0x27, 0xf6, 0x28,
	0x56, 0xb0, 0x44, 0x12, 0x1b, 0xd8, 0x27, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x40, 0x8b,
	0xec, 0x79, 0xd8, 0x00, 0x00, 0x00,
}
